DATA_HEADERS = ['CONVERGED',
                'STEPS_NUM',
                'TRAJECTORY_TYPE',
                'MASS_RANGE',
                'EXT_DIST_ID',
                'WIND_STRENGTH_RANGE',
                'WIND_NOISE_SCALE_RANGE',
                'WIND_DIRECTION_NOISE_SCALE',
                'SINUSOIDAL_WIND_FREQ_RANGE',
                'AGENT_SAMPLES_NUM',
                'AGENT_HANDLING_METHOD ',
                'AGENT_NOISE',
                'AGENT_KERNEL_LENGTH',
                'AGENT_MAX_STEPS',
                'TESTING_POINTS_NUM',
                'CONVERGENCE_N',
                'CONVERGENCE_EPSILON',
                'ACCELERATION_NOISE']

HIPERPARAMETERS = ['NORMALIZE',
                'MODEL',
                'USE_ADAPTIVE',
                'USE_ESTIMATOR',
                'ESTIMATOR_MODE',
                'MPC_MODE',
                'HORIZON',
                'TRAJECTORY_TYPE',
                'MASS_RANGE',
                'EXT_DIST_ID',
                'WIND_STRENGTH_RANGE',
                'WIND_NOISE_SCALE_RANGE',
                'WIND_DIRECTION_NOISE_SCALE',
                'SINUSOIDAL_WIND_FREQ_RANGE',
                'AGENT_SAMPLES_NUM',
                'AGENT_HANDLING_METHOD ',
                'AGENT_NOISE',
                'AGENT_KERNEL_LENGTH',
                'AGENT_MAX_STEPS',
                'TESTING_POINTS_NUM',
                'CONVERGENCE_N',
                'CONVERGENCE_EPSILON',
                'ACCELERATION_NOISE']