from Factories.ToolsFactory.GeneralTools import BidirectionalDict

# COMMANDS TO ASCII BIDIRECTIONAL MAPPING
COMMANDS_ASCII_MAPPING = BidirectionalDict()
COMMANDS_ASCII_MAPPING['ARM_DISARM'] = chr(10)
COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_LOC'] = chr(101)
COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_GLOB'] = chr(102)
COMMANDS_ASCII_MAPPING['TELEMETRY_VELOCITY'] = chr(103)
COMMANDS_ASCII_MAPPING['TELEMETRY_ATTITUDE'] = chr(104)
COMMANDS_ASCII_MAPPING['TELEMETRY_HEADING'] = chr(105)
COMMANDS_ASCII_MAPPING['TELEMETRY_FLIGHT_MODE'] = chr(106)

# ASCII COMMANDS to TelemetryManager methods mapping (subscriptions mapping)
SUBSCRIPTIONS_MAPPING = {
    COMMANDS_ASCII_MAPPING['ARM_DISARM']: ['arm_disarm'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_LOC']: ['update_telemetry', 'printer'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_GLOB']: ['update_telemetry', 'printer'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_VELOCITY']: ['update_telemetry', 'printer'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_ATTITUDE']: ['update_telemetry', 'printer'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_HEADING']: ['update_telemetry', 'printer'],
    COMMANDS_ASCII_MAPPING['TELEMETRY_FLIGHT_MODE']: ['update_telemetry', 'printer'],
}

# COMMANDS DATATYPES MAPPING
COMMANDS_DATATYPES_MAPPING = {
    COMMANDS_ASCII_MAPPING['ARM_DISARM']: 'int8',
    COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_LOC']: 'float32',
    COMMANDS_ASCII_MAPPING['TELEMETRY_POSITION_GLOB']: 'float32',
    COMMANDS_ASCII_MAPPING['TELEMETRY_VELOCITY']: 'float32',
    COMMANDS_ASCII_MAPPING['TELEMETRY_ATTITUDE']: 'float32',
    COMMANDS_ASCII_MAPPING['TELEMETRY_HEADING']: 'float32',
    COMMANDS_ASCII_MAPPING['TELEMETRY_FLIGHT_MODE']: 'int8',
}

# COMMANDS TO TELEMETRY NAMES MAPPING
COMMANDS_TO_TELEMETRY_NAMES = {
    'TELEMETRY_POSITION_LOC': 'position_local',
    'TELEMETRY_POSITION_GLOB': 'position_global',
    'TELEMETRY_VELOCITY': 'velocity',
    'TELEMETRY_ATTITUDE': 'attitude',
    'TELEMETRY_HEADING': 'heading',
    'TELEMETRY_FLIGHT_MODE': 'flight_mode'
}

FLIGHT_MODES_MAPPING = {
    '1': 'STABILIZE',
    '2': 'ACRO',
    '3': 'GUIDED'
}