UAV_COMMAND_AGENT_SUBS = [
    'ARM_DISARM',
    'SET_SPIRAL_SETPOINT:X', 'SET_SPIRAL_SETPOINT:Y', 'SET_SPIRAL_SETPOINT:Z',
    'AUXILIARY_COMMAND',
    'HEARTBEAT',
    'DATA_WRITE',
    'POSITION_CONTROLLER_ON_OFF',
    'ADAPTIVE_CONTROLLER_ON_OFF',
    'ESTIMATOR_ON_OFF',
    'IDENTIFICATION_THROTTLE'
]

UAV_TELEMETRY_AGENT_SUBS = [
]