UAV_COMMAND_AGENT_SUBS = [
    'ARM_DISARM',
    'SET_SPIRAL_SETPOINT:X', 'SET_SPIRAL_SETPOINT:Y', 'SET_SPIRAL_SETPOINT:Z',
    'AUXILIARY_COMMAND',
    'HEARTBEAT',
    'DATA_WRITE',
    'POSITION_CONTROLLER_ON_OFF',
    'ADAPTIVE_CONTROLLER_ON_OFF',
    'ESTIMATOR_ON_OFF',
    'IDENTIFICATION_THROTTLE'
]

UAV_TELEMETRY_AGENT_SUBS = [
]

GCS_SUBS = [
    'TELEMETRY_ESTIMATED_MASS',
    'TELEMETRY_HEADING',
    'TELEMETRY_FLIGHT_MODE',
    'TELEMETRY_THROTTLE_REF',
    'TELEMETRY_BATTERY_VOLTAGE',
    'TELEMETRY_BATTERY_CURRENT',
    'TELEMETRY_WRITING_OK',
    'TELEMETRY_MPC_RUNNING',
    'TELEMETRY_ADAPTIVE_RUNNING',
    'TELEMETRY_POSITION_LOC:X', 'TELEMETRY_POSITION_LOC:Y', 'TELEMETRY_POSITION_LOC:Z',
    'TELEMETRY_POSITION_GLOB:X', 'TELEMETRY_POSITION_GLOB:Y', 'TELEMETRY_POSITION_GLOB:Z',
    'TELEMETRY_VELOCITY:X', 'TELEMETRY_VELOCITY:Y', 'TELEMETRY_VELOCITY:Z',
    'TELEMETRY_ATTITUDE:X', 'TELEMETRY_ATTITUDE:Y', 'TELEMETRY_ATTITUDE:Z',
    'TELEMETRY_CONTROL:X', 'TELEMETRY_CONTROL:Y', 'TELEMETRY_CONTROL:Z',
    'TELEMETRY_ADAPTIVE_CONTROL:X', 'TELEMETRY_ADAPTIVE_CONTROL:Y', 'TELEMETRY_ADAPTIVE_CONTROL:Z',
    'TELEMETRY_UNC_ESTIMATION:X', 'TELEMETRY_UNC_ESTIMATION:Y', 'TELEMETRY_UNC_ESTIMATION:Z',
    'TELEMETRY_CONTROL_OUTPUT:X', 'TELEMETRY_CONTROL_OUTPUT:Y', 'TELEMETRY_CONTROL_OUTPUT:Z'
]